### ISSUE TITLE
关于oss 上传

### ISSUE THREAD

**Issue by StarGods** [xtTech/app-version#15]
1.  配置了oss 相关属性,但是在上转RN包时提示无法初始化.

1. 在上传apk 时   卡在99%  oss里有文件碎片 查询 oss错误码得知 分片上传 合并时出了问题

`  <?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>InvalidPart</Code>
  <Message>One or more of the specified parts could not be found or the specified entity tag might not have matched the part's entity tag.</Message>
  <RequestId>5F09E53B25D95C3235741737</RequestId>
  <HostId>xking.oss-cn-hangzhou.aliyuncs.com</HostId>
  <ETag>undefined</ETag>
  <PartNumber>1</PartNumber>
  <UploadId>299AEA32DDE14A828E023EF962E947BA</UploadId>
</Error>
`

**Comment by zcbin88** [comment]
请问解决了吗，我也遇到这个问题
